//DO NOT EDIT THIS FILE DIRECTLY! Use the editor provided under Window/PhysSound.
namespace PhysSound
{
    public class PhysSoundTypeList
    {
        public static string[] PhysSoundTypes = new string[5] { "Hard", "Soft", "Other", "Metal", "Liquid" };

        public static string GetKey(int index) => (index >= PhysSoundTypes.Length) || (index < 0) ? "" : PhysSoundTypes[index];

        public static bool HasKey(int index) => index < PhysSoundTypes.Length && index >= 0;
    }
}